### ISSUE TITLE
Húsleves recept

### ISSUE THREAD

**Issue by norbert-gemes** [nitslaszlo/Receptek9A#10]
Keress a neten egy húsleves receptet, majd ásold be a húsleves.txt állományban!

**Comment by norbert-gemes** [comment]
Hajrá Mátyás!Ne csalódjak benned!

**Comment by bokamatyas** [comment]
Egy húslevest csak nem cseszek el.

**Comment by norbert-gemes** [comment]
Figyelj kaptál egy könnyebbet,de aztán nehogy elrontsd!

**Comment by norbert-gemes** [comment]
kész?

**Comment by norbert-gemes** [comment]
Aztán csináld ám meg!
