### ISSUE TITLE
Rakott krumpli recept

### ISSUE THREAD

**Issue by benczesara** [nitslaszlo/Receptek9A#5]
Keress a neten egy rakott krumpli receptet, majd másold be a rakottkrumpli.txt állományba.

**Comment by benczesara** [comment]
Tessék, viheted xD

**Comment by FoldiDaniel** [comment]
Köszi

**Comment by FoldiDaniel** [comment]
Van valami különleges kívánság, vagy bármilyen rakott krumpli jó?
